ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'PROPOSAL_SENT';
ALTER TYPE "ActivityStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "LeadHistoryEntryType" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_STATUS_CHANGED';
ALTER TYPE "LeadDomainEventName" ADD VALUE IF NOT EXISTS 'FollowUpStatusChanged';
