export const BUSINESS_ROLES = ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"] as const;
export type BusinessRoleCode = (typeof BUSINESS_ROLES)[number];

export const OPERATIONS_REVIEWER = "OPERATIONS_REVIEWER" as const;

export const PermissionCode = {
  UsersManage: "users.manage",
  UsersRead: "users.read",
  RolesAssign: "roles.assign",
  PermissionsRead: "permissions.read",
  TeamsManage: "teams.manage",
  TeamsRead: "teams.read",
  ProfileRead: "profile.read",
  AuditRead: "audit.read",
  DashboardOperationsView: "dashboard.operations.view",
  ActivitiesSearch: "activities.search",
  ActivitiesCreate: "activities.create",
  ActivitiesRead: "activities.read",
  ActivitiesManage: "activities.manage",
  ExhibitionsSearch: "exhibitions.search",
  ExhibitionsCreate: "exhibitions.create",
  ExhibitionsRead: "exhibitions.read",
  ExhibitionsUpdate: "exhibitions.update",
  ExhibitionsArchive: "exhibitions.archive",
  ExhibitionsRestore: "exhibitions.restore",
  ExhibitionsAssignAttendee: "exhibitions.assign_attendee",
  ExhibitionsConfirmAttendance: "exhibitions.confirm_attendance",
  ExhibitionsAttributeLead: "exhibitions.attribute_lead",
  ExhibitionsViewSummary: "exhibitions.view_summary",
  LeadsCreate: "leads.create",
  LeadsRead: "leads.read",
  LeadsUpdate: "leads.update",
  LeadsAssign: "leads.assign",
  LeadsStatusChange: "leads.status.change",
  LeadsNoteAdd: "leads.note.add",
  LeadsHistoryRead: "leads.history.read",
  LeadsSearch: "leads.search",
} as const;

export type PermissionCode = (typeof PermissionCode)[keyof typeof PermissionCode];

export interface PermissionDefinition {
  code: PermissionCode;
  resource: string;
  action: string;
  description: string;
  grantedTo: string[];
}

export const PERMISSION_MATRIX: PermissionDefinition[] = [
  {
    code: PermissionCode.UsersManage,
    resource: "users",
    action: "manage",
    description: "Create, update, disable, and re-enable users",
    grantedTo: ["ADMIN"],
  },
  {
    code: PermissionCode.UsersRead,
    resource: "users",
    action: "read",
    description: "View user records",
    grantedTo: ["ADMIN", "MANAGER"],
  },
  {
    code: PermissionCode.RolesAssign,
    resource: "roles",
    action: "assign",
    description: "Assign fixed business roles and reviewer access",
    grantedTo: ["ADMIN"],
  },
  {
    code: PermissionCode.PermissionsRead,
    resource: "permissions",
    action: "read",
    description: "Inspect the fixed permission matrix",
    grantedTo: ["ADMIN"],
  },
  {
    code: PermissionCode.TeamsManage,
    resource: "teams",
    action: "manage",
    description: "Create, update, and assign teams",
    grantedTo: ["ADMIN"],
  },
  {
    code: PermissionCode.TeamsRead,
    resource: "teams",
    action: "read",
    description: "View permitted team scope",
    grantedTo: ["ADMIN", "MANAGER"],
  },
  {
    code: PermissionCode.ProfileRead,
    resource: "profile",
    action: "read",
    description: "View own profile and role summary",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.AuditRead,
    resource: "audit",
    action: "read",
    description: "Search security audit activity",
    grantedTo: ["ADMIN", OPERATIONS_REVIEWER],
  },
  {
    code: PermissionCode.DashboardOperationsView,
    resource: "dashboard",
    action: "view_operations",
    description: "View operations dashboard metrics",
    grantedTo: ["ADMIN", "MANAGER"],
  },
  {
    code: PermissionCode.ActivitiesSearch,
    resource: "activities",
    action: "search",
    description: "Search permitted activities",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.ActivitiesCreate,
    resource: "activities",
    action: "create",
    description: "Create activities in permitted CRM scope",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.ActivitiesRead,
    resource: "activities",
    action: "read",
    description: "View permitted lead activity timelines",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.ActivitiesManage,
    resource: "activities",
    action: "manage",
    description: "Complete, reassign, and cancel permitted activities",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.ExhibitionsSearch,
    resource: "exhibitions",
    action: "search",
    description: "Search permitted exhibitions",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.ExhibitionsCreate,
    resource: "exhibitions",
    action: "create",
    description: "Create exhibitions in permitted CRM scope",
    grantedTo: ["ADMIN", "MANAGER"],
  },
  {
    code: PermissionCode.ExhibitionsRead,
    resource: "exhibitions",
    action: "read",
    description: "View permitted exhibitions",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.ExhibitionsUpdate,
    resource: "exhibitions",
    action: "update",
    description: "Update permitted exhibitions",
    grantedTo: ["ADMIN", "MANAGER"],
  },
  {
    code: PermissionCode.ExhibitionsArchive,
    resource: "exhibitions",
    action: "archive",
    description: "Archive exhibitions",
    grantedTo: ["ADMIN", "MANAGER"],
  },
  {
    code: PermissionCode.ExhibitionsRestore,
    resource: "exhibitions",
    action: "restore",
    description: "Restore archived exhibitions",
    grantedTo: ["ADMIN", "MANAGER"],
  },
  {
    code: PermissionCode.ExhibitionsAssignAttendee,
    resource: "exhibitions",
    action: "assign_attendee",
    description: "Assign exhibition attendees",
    grantedTo: ["ADMIN", "MANAGER"],
  },
  {
    code: PermissionCode.ExhibitionsConfirmAttendance,
    resource: "exhibitions",
    action: "confirm_attendance",
    description: "Confirm exhibition attendance",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.ExhibitionsAttributeLead,
    resource: "exhibitions",
    action: "attribute_lead",
    description: "Attribute leads to exhibitions",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.ExhibitionsViewSummary,
    resource: "exhibitions",
    action: "view_summary",
    description: "Review exhibition performance summary",
    grantedTo: ["ADMIN", "MANAGER"],
  },
  {
    code: PermissionCode.LeadsCreate,
    resource: "leads",
    action: "create",
    description: "Create leads in permitted CRM scope",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.LeadsRead,
    resource: "leads",
    action: "read",
    description: "View permitted lead records",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.LeadsUpdate,
    resource: "leads",
    action: "update",
    description: "Update permitted lead records",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.LeadsAssign,
    resource: "leads",
    action: "assign",
    description: "Assign or reassign leads",
    grantedTo: ["ADMIN", "MANAGER"],
  },
  {
    code: PermissionCode.LeadsStatusChange,
    resource: "leads",
    action: "change_status",
    description: "Change lead pipeline status",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.LeadsNoteAdd,
    resource: "leads",
    action: "add_note",
    description: "Add append-only lead notes",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.LeadsHistoryRead,
    resource: "leads",
    action: "read_history",
    description: "View permitted lead history",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
  {
    code: PermissionCode.LeadsSearch,
    resource: "leads",
    action: "search",
    description: "Search permitted lead records",
    grantedTo: ["ADMIN", "MANAGER", "SALES_REPRESENTATIVE"],
  },
];
